server:
  env_name: prod
  port: 8000
  cors:
    allow_origins: ["*"]
    allow_methods: ["*"]
    allow_credentials: true

llm:
  mode: gemini

tokenizer: null

embedding:
  mode: gemini

gemini:
  api_key: ${GOOGLE_API_KEY}
  # Use 'gemini-1.5-pro' instead of 'gemini-pro'
  model: models/gemini-1.5-pro
  # Use 'text-embedding-004' for the latest embedding support
  embedding_model: models/text-embedding-004

vectorstore:
  database: qdrant

qdrant:
  path: local_data/qdrant
